Import Global setting

In [1]:
import pandas as pd
import numpy as np
import lightgbm as lgb

from itertools import product

RANDOM_STATE = 42

Load train/val/test features

In [2]:
train_feat = pd.read_parquet("data/train_features.parquet")
val_feat = pd.read_parquet("data/val_features.parquet")
full_train_feat = pd.read_parquet("data/full_train_features.parquet")
test_feat = pd.read_parquet("data/full_test_features.parquet")

Feature selection

In [3]:
# These columns are not used as model inputs.
# srch_id and prop_id are kept separately for grouping/submission.
NON_FEATURE_COLS = [
    "srch_id",
    "prop_id",
    "date_time",
    "click_bool",
    "booking_bool",
    "gross_bookings_usd",
    "position",
    "relevance"
]

# Keep only numeric columns as model features.
feature_cols = [
    col for col in train_feat.columns
    if col not in NON_FEATURE_COLS
    and pd.api.types.is_numeric_dtype(train_feat[col])
]

# Make sure validation has exactly the same features.
missing_in_val = set(feature_cols) - set(val_feat.columns)
extra_in_val = set(val_feat.columns) - set(train_feat.columns)

print("Number of features:", len(feature_cols))
print("Missing in validation:", missing_in_val)
print("Extra in validation:", len(extra_in_val))

print(feature_cols[:50])

Number of features: 169
Missing in validation: set()
Extra in validation: 0
['site_id', 'visitor_location_country_id', 'visitor_hist_starrating', 'visitor_hist_adr_usd', 'prop_country_id', 'prop_starrating', 'prop_review_score', 'prop_brand_bool', 'prop_location_score1', 'prop_location_score2', 'prop_log_historical_price', 'price_usd', 'promotion_flag', 'srch_destination_id', 'srch_length_of_stay', 'srch_booking_window', 'srch_adults_count', 'srch_children_count', 'srch_room_count', 'srch_saturday_night_bool', 'srch_query_affinity_score', 'orig_destination_distance', 'random_bool', 'comp1_rate', 'comp1_inv', 'comp1_rate_percent_diff', 'comp2_rate', 'comp2_inv', 'comp2_rate_percent_diff', 'comp3_rate', 'comp3_inv', 'comp3_rate_percent_diff', 'comp4_rate', 'comp4_inv', 'comp4_rate_percent_diff', 'comp5_rate', 'comp5_inv', 'comp5_rate_percent_diff', 'comp6_rate', 'comp6_inv', 'comp6_rate_percent_diff', 'comp7_rate', 'comp7_inv', 'comp7_rate_percent_diff', 'comp8_rate', 'comp8_inv', 'comp8_rate_percent_diff', 'visitor_hist_starrating_missing', 'visitor_hist_adr_usd_missing', 'srch_query_affinity_score_missing']

Preparing Ranking Model Inputs

In [4]:
# LightGBM ranker needs rows sorted by search group to identify which rows belong to the same search.
train_feat = train_feat.sort_values("srch_id").reset_index(drop=True)
val_feat = val_feat.sort_values("srch_id").reset_index(drop=True)

X_train = train_feat[feature_cols]
y_train = train_feat["relevance"].astype(int)

X_val = val_feat[feature_cols]
y_val = val_feat["relevance"].astype(int)

# Group sizes are needed for LightGBM ranker to know how many rows belong to each search group.
group_train = train_feat.groupby("srch_id").size().to_numpy()
group_val = val_feat.groupby("srch_id").size().to_numpy()

print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("Number of train groups:", len(group_train))
print("Number of validation groups:", len(group_val))
print("First 10 group sizes:", group_train[:10])

X_train: (3980039, 169)
X_val: (978308, 169)
Number of train groups: 159836
Number of validation groups: 39959
First 10 group sizes: [28 32 21 33 28 31 29 33 34 16]

Evaluate the ranking quality of the model using NDCG@k metric.

In [5]:
def dcg_at_k(relevances, k=5):
    """
    Computes DCG@k for one ranked list.
    """
    relevances = np.asarray(relevances)[:k]
    if len(relevances) == 0:
        return 0.0

    discounts = np.log2(np.arange(2, len(relevances) + 2))
    gains = (2 ** relevances - 1)
    return np.sum(gains / discounts)


def ndcg_at_k_for_group(y_true, y_score, k=5):
    """
    Computes NDCG@k for one search group.
    """
    order = np.argsort(-y_score)
    ranked_relevance = y_true[order]

    ideal_order = np.argsort(-y_true)
    ideal_relevance = y_true[ideal_order]

    dcg = dcg_at_k(ranked_relevance, k=k)
    idcg = dcg_at_k(ideal_relevance, k=k)

    if idcg == 0:
        return 0.0

    return dcg / idcg


def mean_ndcg_at_k(df, y_true_col, y_score_col, group_col="srch_id", k=5):
    """
    Computes mean NDCG@k over all searches.
    """

    scores = []

    for _, group in df.groupby(group_col):
        y_true = group[y_true_col].to_numpy()
        y_score = group[y_score_col].to_numpy()

        scores.append(ndcg_at_k_for_group(y_true, y_score, k=k))

    return np.mean(scores)

Binary Classification model - LGBMClassifier Model

In [ ]:
# ---------------------------------------------------
# Binary classification target
# ---------------------------------------------------

y_train_cls = (
    (train_feat["click_bool"] == 1) |
    (train_feat["booking_bool"] == 1)
).astype(int)

y_val_cls = (
    (val_feat["click_bool"] == 1) |
    (val_feat["booking_bool"] == 1)
).astype(int)

# ---------------------------------------------------
# Train classifier
# ---------------------------------------------------
param_grid = {
    "num_leaves": [31, 63],
    "learning_rate": [0.05, 0.03],
    "min_child_samples": [50, 100]
}

keys = list(param_grid.keys())

experiments = [
    dict(zip(keys, values))
    for values in product(*param_grid.values())
]

classifier_results = []

for i, params in enumerate(experiments, start=1):
    print(f"Training classifier {i}/{len(experiments)}")
    print(params)

    classifier = lgb.LGBMClassifier(
        objective="binary",

        n_estimators=1000,

        subsample=0.8,
        colsample_bytree=0.8,

        random_state=RANDOM_STATE,
        n_jobs=-1,

        **params
    )

    classifier.fit(
        X_train,
        y_train_cls,
        eval_set=[(X_val, y_val_cls)],
        eval_metric="auc",

        callbacks=[
            lgb.early_stopping(50),
            lgb.log_evaluation(100)
        ]
    )

    # ---------------------------------------------------
    # Predict probabilities
    # ---------------------------------------------------

    preds = classifier.predict_proba(
            X_val,
            num_iteration=classifier.best_iteration_
        )[:, 1]


    # ---------------------------------------------------
    # Evaluate ranking quality using NDCG
    # ---------------------------------------------------

    val_classifier_eval = val_feat[
            ["srch_id", "prop_id", "relevance"]
        ].copy()

    val_classifier_eval["prediction"] = preds

    classifier_ndcg = mean_ndcg_at_k(
        val_classifier_eval,
        y_true_col="relevance",
        y_score_col="prediction",
        group_col="srch_id",
        k=5
    )

    classifier_results.append({
            "experiment": i,

            "num_leaves": params["num_leaves"],
            "learning_rate": params["learning_rate"],
            "min_child_samples": params["min_child_samples"],

            "best_iteration": classifier.best_iteration_,
            "validation_ndcg@5": classifier_ndcg
        })

classifier_results = pd.DataFrame(classifier_results)

classifier_results = classifier_results.sort_values(
        "validation_ndcg@5",
        ascending=False
    )

best_classifier_parameters = {
    "num_leaves": int(classifier_results.iloc[0]["num_leaves"]),
    "learning_rate": float(classifier_results.iloc[0]["learning_rate"]),
    "min_child_samples": int(classifier_results.iloc[0]["min_child_samples"]),
}

print(best_classifier_parameters)
display(classifier_results)

Training classifier 1/8
{'num_leaves': 31, 'learning_rate': 0.05, 'min_child_samples': 50}
Training classifier 2/8
{'num_leaves': 31, 'learning_rate': 0.05, 'min_child_samples': 100}
Training classifier 3/8
{'num_leaves': 31, 'learning_rate': 0.03, 'min_child_samples': 50}
Training classifier 4/8
{'num_leaves': 31, 'learning_rate': 0.03, 'min_child_samples': 100}
Training classifier 5/8
{'num_leaves': 63, 'learning_rate': 0.05, 'min_child_samples': 50}
Training classifier 6/8
{'num_leaves': 63, 'learning_rate': 0.05, 'min_child_samples': 100}
Training classifier 7/8
{'num_leaves': 63, 'learning_rate': 0.03, 'min_child_samples': 50}
Training classifier 8/8
{'num_leaves': 63, 'learning_rate': 0.03, 'min_child_samples': 100}
[LightGBM] [Info] Number of positive: 177702, number of negative: 3802337
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.194223 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.044648 -> initscore=-3.063263
[LightGBM] [Info] Start training from score -3.063263
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.748711	valid_0's binary_logloss: 0.165172
[200]	valid_0's auc: 0.750648	valid_0's binary_logloss: 0.165039
Early stopping, best iteration is:
[159]	valid_0's auc: 0.75137	valid_0's binary_logloss: 0.164648
{'num_leaves': 63, 'learning_rate': 0.03, 'min_child_samples': 100}

,experiment,num_leaves,learning_rate,min_child_samples,best_iteration,validation_ndcg@5
0,8,63,0.03,100,159,0.373545

LGBMRanker Model

In [7]:
# ---------------------------------------------------
# Hyperparameter grid
# ---------------------------------------------------

param_grid = {
    "num_leaves": [31, 63, 127],
    "learning_rate": [0.05, 0.01, 0.1],
    "min_child_samples": [50, 100, 200]
}

# Create all parameter combinations
keys = list(param_grid.keys())

experiments = [
    dict(zip(keys, values))
    for values in product(*param_grid.values())
]

print("Total experiments:", len(experiments))

# ---------------------------------------------------
# Run experiments
# ---------------------------------------------------

tuning_results = []

for i, params in enumerate(experiments, start=1):

    print("=" * 60)
    print(f"Experiment {i}/{len(experiments)}")
    print(params)

    ranker = lgb.LGBMRanker(
        objective="lambdarank",
        metric="ndcg",
        ndcg_eval_at=[5],
        boosting_type="gbdt",

        n_estimators=1000,

        subsample=0.8,
        colsample_bytree=0.8,

        random_state=RANDOM_STATE,
        n_jobs=-1,

        **params
    )

    ranker.fit(
        X_train,
        y_train,
        group=group_train,

        eval_set=[(X_val, y_val)],
        eval_group=[group_val],
        eval_at=[5],

        callbacks=[
            lgb.early_stopping(stopping_rounds=50),
            lgb.log_evaluation(period=100)
        ]
    )

    # -------------------------
    # Predict validation scores
    # -------------------------

    preds = ranker.predict(
        X_val,
        num_iteration=ranker.best_iteration_
    )

    # -------------------------
    # Compute validation NDCG@5
    # -------------------------

    tmp = val_feat[["srch_id", "prop_id", "relevance"]].copy()

    tmp["prediction"] = preds

    score = mean_ndcg_at_k(
        tmp,
        y_true_col="relevance",
        y_score_col="prediction",
        group_col="srch_id",
        k=5
    )

    # -------------------------
    # Save results
    # -------------------------

    tuning_results.append({
        "experiment": i,

        "num_leaves": params["num_leaves"],
        "learning_rate": params["learning_rate"],
        "min_child_samples": params["min_child_samples"],

        "best_iteration": ranker.best_iteration_,
        "validation_ndcg@5": score
    })

# ---------------------------------------------------
# Final results table
# ---------------------------------------------------

tuning_results = pd.DataFrame(tuning_results)

tuning_results = tuning_results.sort_values(
    "validation_ndcg@5",
    ascending=False
)

best_parameters = {
    "num_leaves": int(tuning_results.iloc[0]["num_leaves"]),
    "learning_rate": float(tuning_results.iloc[0]["learning_rate"]),
    "min_child_samples": int(tuning_results.iloc[0]["min_child_samples"])
}

display(tuning_results)

Total experiments: 27
============================================================
Experiment 1/27
{'num_leaves': 31, 'learning_rate': 0.05, 'min_child_samples': 50}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.179577 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16614
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 169
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.377182
Early stopping, best iteration is:
[120]	valid_0's ndcg@5: 0.377688

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 2/27
{'num_leaves': 31, 'learning_rate': 0.05, 'min_child_samples': 100}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.218260 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.37427
[200]	valid_0's ndcg@5: 0.376272
Early stopping, best iteration is:
[198]	valid_0's ndcg@5: 0.376686

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 3/27
{'num_leaves': 31, 'learning_rate': 0.05, 'min_child_samples': 200}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.172564 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.37427
[200]	valid_0's ndcg@5: 0.376108
Early stopping, best iteration is:
[195]	valid_0's ndcg@5: 0.376551

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 4/27
{'num_leaves': 31, 'learning_rate': 0.01, 'min_child_samples': 50}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.169574 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16614
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 169
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.368387
[200]	valid_0's ndcg@5: 0.371294
[300]	valid_0's ndcg@5: 0.373422
[400]	valid_0's ndcg@5: 0.374137
[500]	valid_0's ndcg@5: 0.375727
Early stopping, best iteration is:
[529]	valid_0's ndcg@5: 0.376261

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 5/27
{'num_leaves': 31, 'learning_rate': 0.01, 'min_child_samples': 100}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.176830 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.369259
[200]	valid_0's ndcg@5: 0.370855
[300]	valid_0's ndcg@5: 0.373527
Early stopping, best iteration is:
[349]	valid_0's ndcg@5: 0.374542

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 6/27
{'num_leaves': 31, 'learning_rate': 0.01, 'min_child_samples': 200}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.178888 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.369259
[200]	valid_0's ndcg@5: 0.370855
[300]	valid_0's ndcg@5: 0.373527
[400]	valid_0's ndcg@5: 0.374559
Early stopping, best iteration is:
[419]	valid_0's ndcg@5: 0.375136

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 7/27
{'num_leaves': 31, 'learning_rate': 0.1, 'min_child_samples': 50}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.167189 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16614
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 169
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.376385
Early stopping, best iteration is:
[96]	valid_0's ndcg@5: 0.378319

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 8/27
{'num_leaves': 31, 'learning_rate': 0.1, 'min_child_samples': 100}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.185285 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.376248
Early stopping, best iteration is:
[105]	valid_0's ndcg@5: 0.376924

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 9/27
{'num_leaves': 31, 'learning_rate': 0.1, 'min_child_samples': 200}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.172915 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.373932
Early stopping, best iteration is:
[63]	valid_0's ndcg@5: 0.375294

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 10/27
{'num_leaves': 63, 'learning_rate': 0.05, 'min_child_samples': 50}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.170218 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16614
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 169
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.376338
Early stopping, best iteration is:
[96]	valid_0's ndcg@5: 0.377553

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 11/27
{'num_leaves': 63, 'learning_rate': 0.05, 'min_child_samples': 100}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.194759 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.377751
Early stopping, best iteration is:
[146]	valid_0's ndcg@5: 0.37964

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 12/27
{'num_leaves': 63, 'learning_rate': 0.05, 'min_child_samples': 200}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.167159 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.377456
[200]	valid_0's ndcg@5: 0.378278
Early stopping, best iteration is:
[173]	valid_0's ndcg@5: 0.378807

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 13/27
{'num_leaves': 63, 'learning_rate': 0.01, 'min_child_samples': 50}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.180721 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16614
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 169
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.372626
[200]	valid_0's ndcg@5: 0.375112
[300]	valid_0's ndcg@5: 0.377094
Early stopping, best iteration is:
[277]	valid_0's ndcg@5: 0.377499

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 14/27
{'num_leaves': 63, 'learning_rate': 0.01, 'min_child_samples': 100}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.175087 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.37331
[200]	valid_0's ndcg@5: 0.37523
[300]	valid_0's ndcg@5: 0.376452
[400]	valid_0's ndcg@5: 0.377771
[500]	valid_0's ndcg@5: 0.378533
Early stopping, best iteration is:
[507]	valid_0's ndcg@5: 0.378875

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 15/27
{'num_leaves': 63, 'learning_rate': 0.01, 'min_child_samples': 200}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.179790 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.37331
[200]	valid_0's ndcg@5: 0.37523
[300]	valid_0's ndcg@5: 0.376452
[400]	valid_0's ndcg@5: 0.377702
[500]	valid_0's ndcg@5: 0.378585
Early stopping, best iteration is:
[536]	valid_0's ndcg@5: 0.378935

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 16/27
{'num_leaves': 63, 'learning_rate': 0.1, 'min_child_samples': 50}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.183305 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16614
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 169
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.377773
Early stopping, best iteration is:
[113]	valid_0's ndcg@5: 0.37812

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 17/27
{'num_leaves': 63, 'learning_rate': 0.1, 'min_child_samples': 100}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.168845 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.375092
Early stopping, best iteration is:
[70]	valid_0's ndcg@5: 0.377467

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 18/27
{'num_leaves': 63, 'learning_rate': 0.1, 'min_child_samples': 200}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.166118 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.377051
Early stopping, best iteration is:
[75]	valid_0's ndcg@5: 0.378753

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 19/27
{'num_leaves': 127, 'learning_rate': 0.05, 'min_child_samples': 50}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.214924 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16614
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 169
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.380282
Early stopping, best iteration is:
[122]	valid_0's ndcg@5: 0.381279

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 20/27
{'num_leaves': 127, 'learning_rate': 0.05, 'min_child_samples': 100}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.191997 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.380602
Early stopping, best iteration is:
[142]	valid_0's ndcg@5: 0.381273

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 21/27
{'num_leaves': 127, 'learning_rate': 0.05, 'min_child_samples': 200}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.167845 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.379371
Early stopping, best iteration is:
[126]	valid_0's ndcg@5: 0.380914

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 22/27
{'num_leaves': 127, 'learning_rate': 0.01, 'min_child_samples': 50}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.197567 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16614
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 169
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.376054
[200]	valid_0's ndcg@5: 0.378501
[300]	valid_0's ndcg@5: 0.379842
[400]	valid_0's ndcg@5: 0.380373
[500]	valid_0's ndcg@5: 0.381383
Early stopping, best iteration is:
[496]	valid_0's ndcg@5: 0.381703

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 23/27
{'num_leaves': 127, 'learning_rate': 0.01, 'min_child_samples': 100}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.207817 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.376625
[200]	valid_0's ndcg@5: 0.378838
[300]	valid_0's ndcg@5: 0.379763
Early stopping, best iteration is:
[323]	valid_0's ndcg@5: 0.380369

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 24/27
{'num_leaves': 127, 'learning_rate': 0.01, 'min_child_samples': 200}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.188662 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.376636
[200]	valid_0's ndcg@5: 0.378703
[300]	valid_0's ndcg@5: 0.380555
Early stopping, best iteration is:
[256]	valid_0's ndcg@5: 0.380673

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 25/27
{'num_leaves': 127, 'learning_rate': 0.1, 'min_child_samples': 50}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.177465 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16614
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 169
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.372435
Early stopping, best iteration is:
[64]	valid_0's ndcg@5: 0.377435

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 26/27
{'num_leaves': 127, 'learning_rate': 0.1, 'min_child_samples': 100}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.169329 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.37803
Early stopping, best iteration is:
[95]	valid_0's ndcg@5: 0.379348

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 27/27
{'num_leaves': 127, 'learning_rate': 0.1, 'min_child_samples': 200}

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.200221 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16612
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.378985
Early stopping, best iteration is:
[82]	valid_0's ndcg@5: 0.37969

c:\Users\Emmanuella\miniconda3\envs\dmt_a2\Lib\site-packages\lightgbm\sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

,experiment,num_leaves,learning_rate,min_child_samples,best_iteration,validation_ndcg@5
21,22,127,0.01,50,496,0.381703
18,19,127,0.05,50,122,0.381278
19,20,127,0.05,100,142,0.381272
20,21,127,0.05,200,126,0.380914
23,24,127,0.01,200,256,0.380673
22,23,127,0.01,100,323,0.380367
26,27,127,0.10,200,82,0.379691
10,11,63,0.05,100,146,0.379640
25,26,127,0.10,100,95,0.379348
14,15,63,0.01,200,536,0.378935
13,14,63,0.01,100,507,0.378875
11,12,63,0.05,200,173,0.378807
17,18,63,0.10,200,75,0.378753
6,7,31,0.10,50,96,0.378326
15,16,63,0.10,50,113,0.378120
0,1,31,0.05,50,120,0.377688
9,10,63,0.05,50,96,0.377563
12,13,63,0.01,50,277,0.377499
16,17,63,0.10,100,70,0.377467
24,25,127,0.10,50,64,0.377435
7,8,31,0.10,100,105,0.376925
1,2,31,0.05,100,198,0.376686
2,3,31,0.05,200,195,0.376551
3,4,31,0.01,50,529,0.376261
8,9,31,0.10,200,63,0.375298
5,6,31,0.01,200,419,0.375136
4,5,31,0.01,100,349,0.374542

In [ ]:
# Rebuild feature list from full training data.
final_feature_cols = [
    col for col in full_train_feat.columns
    if col not in NON_FEATURE_COLS
    and pd.api.types.is_numeric_dtype(full_train_feat[col])
]

# Ensure test has all final feature columns.
missing_in_test = [col for col in final_feature_cols if col not in test_feat.columns]
print("Missing features in test:", missing_in_test)

# Sort by srch_id to ensure correct grouping for LightGBM ranker.
full_train_feat = full_train_feat.sort_values("srch_id").reset_index(drop=True)
test_feat = test_feat.sort_values("srch_id").reset_index(drop=True)

X_full = full_train_feat[final_feature_cols]
y_full = full_train_feat["relevance"].astype(int)
group_full = full_train_feat.groupby("srch_id").size().to_numpy()

X_test = test_feat[final_feature_cols]

print("X_full:", X_full.shape)
print("X_test:", X_test.shape)
print("Number of final features:", len(final_feature_cols))

In [ ]:
# Use the best iteration from validation if available.
# If early stopping stopped at e.g. 350 trees, train final model with that many trees.
best_cls_n_estimators = ranker.best_iteration_

final_classifier = lgb.LGBMClassifier(
    objective="binary",

    n_estimators=best_cls_n_estimators,
    num_leaves=best_classifier_parameters["num_leaves"],
    learning_rate=best_classifier_parameters["learning_rate"],
    min_child_samples=best_classifier_parameters["min_child_samples"],

    subsample=0.8,
    colsample_bytree=0.8,

    random_state=RANDOM_STATE,
    n_jobs=-1
)

In [ ]:
# Use the best iteration from validation if available.
# If early stopping stopped at e.g. 350 trees, train final model with that many trees.
best_n_estimators = ranker.best_iteration_

print("Training final model with n_estimators =", best_n_estimators)

final_ranker = lgb.LGBMRanker(
    objective="lambdarank",
    metric="ndcg",
    ndcg_eval_at=[5],
    boosting_type="gbdt",

    n_estimators=best_n_estimators,
    learning_rate=best_parameters["learning_rate"],
    num_leaves=best_parameters["num_leaves"],
    max_depth=-1,
    min_child_samples=best_parameters["min_child_samples"],
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=RANDOM_STATE,
    n_jobs=-1
)

final_ranker.fit(
    X_full,
    y_full,
    group=group_full
)

In [ ]:
test_scores = final_ranker.predict(test_feat)

submission = test_feat[["srch_id", "prop_id"]].copy()
submission["score"] = test_scores

# Sort hotels within each search by predicted score descending.
submission = submission.sort_values(
    ["srch_id", "score"],
    ascending=[True, False]
)

# Required Kaggle format:
# SearchId,PropertyId
submission = submission.rename(columns={
    "srch_id": "SearchId",
    "prop_id": "PropertyId"
})

submission = submission[["SearchId", "PropertyId"]]

display(submission.head(30))

submission_path = "submission_lgbm_ranker.csv"
submission.to_csv(submission_path, index=False)

print("Saved submission to:", submission_path)
print("Submission shape:", submission.shape)

In [ ]:
final_feature_importance = pd.DataFrame({
    "feature": final_feature_cols,
    "importance": final_ranker.feature_importances_
}).sort_values("importance", ascending=False)

display(final_feature_importance.head(50))

final_feature_importance.to_csv("feature_importance_lgbm_ranker.csv", index=False)
print("Saved feature importance to feature_importance_lgbm_ranker.csv")