Import Global setting

In [16]:
import pandas as pd
import numpy as np
import lightgbm as lgb

from itertools import product

RANDOM_STATE = 42

Load train/val/test features

In [17]:
train_feat = pd.read_parquet("data/train_features.parquet")
val_feat = pd.read_parquet("data/val_features.parquet")
full_train_feat = pd.read_parquet("data/full_train_features.parquet")
test_feat = pd.read_parquet("data/full_test_features.parquet")

Feature selection

In [18]:
# These columns are not used as model inputs.
# srch_id and prop_id are kept separately for grouping/submission.
NON_FEATURE_COLS = [
    "srch_id",
    "prop_id",
    "date_time",
    "click_bool",
    "booking_bool",
    "gross_bookings_usd",
    "position",
    "relevance"
]

# Keep only numeric columns as model features.
feature_cols = [
    col for col in train_feat.columns
    if col not in NON_FEATURE_COLS
    and pd.api.types.is_numeric_dtype(train_feat[col])
]

# Make sure validation has exactly the same features.
missing_in_val = set(feature_cols) - set(val_feat.columns)
extra_in_val = set(val_feat.columns) - set(train_feat.columns)

print("Number of features:", len(feature_cols))
print("Missing in validation:", missing_in_val)
print("Extra in validation:", len(extra_in_val))

print(feature_cols[:50])

Number of features: 169
Missing in validation: set()
Extra in validation: 0
['site_id', 'visitor_location_country_id', 'visitor_hist_starrating', 'visitor_hist_adr_usd', 'prop_country_id', 'prop_starrating', 'prop_review_score', 'prop_brand_bool', 'prop_location_score1', 'prop_location_score2', 'prop_log_historical_price', 'price_usd', 'promotion_flag', 'srch_destination_id', 'srch_length_of_stay', 'srch_booking_window', 'srch_adults_count', 'srch_children_count', 'srch_room_count', 'srch_saturday_night_bool', 'srch_query_affinity_score', 'orig_destination_distance', 'random_bool', 'comp1_rate', 'comp1_inv', 'comp1_rate_percent_diff', 'comp2_rate', 'comp2_inv', 'comp2_rate_percent_diff', 'comp3_rate', 'comp3_inv', 'comp3_rate_percent_diff', 'comp4_rate', 'comp4_inv', 'comp4_rate_percent_diff', 'comp5_rate', 'comp5_inv', 'comp5_rate_percent_diff', 'comp6_rate', 'comp6_inv', 'comp6_rate_percent_diff', 'comp7_rate', 'comp7_inv', 'comp7_rate_percent_diff', 'comp8_rate', 'comp8_inv', 'comp8_rate_percent_diff', 'visitor_hist_starrating_missing', 'visitor_hist_adr_usd_missing', 'srch_query_affinity_score_missing']

Preparing Ranking Model Inputs

In [19]:
# LightGBM ranker needs rows sorted by search group to identify which rows belong to the same search.
train_feat = train_feat.sort_values("srch_id").reset_index(drop=True)
val_feat = val_feat.sort_values("srch_id").reset_index(drop=True)

X_train = train_feat[feature_cols]
y_train = train_feat["relevance"].astype(int)

X_val = val_feat[feature_cols]
y_val = val_feat["relevance"].astype(int)

# Group sizes are needed for LightGBM ranker to know how many rows belong to each search group.
group_train = train_feat.groupby("srch_id").size().to_numpy()
group_val = val_feat.groupby("srch_id").size().to_numpy()

print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("Number of train groups:", len(group_train))
print("Number of validation groups:", len(group_val))
print("First 10 group sizes:", group_train[:10])

X_train: (3980039, 169)
X_val: (978308, 169)
Number of train groups: 159836
Number of validation groups: 39959
First 10 group sizes: [28 32 21 33 28 31 29 33 34 16]

Evaluate the ranking quality of the model using NDCG@k metric.

In [20]:
def dcg_at_k(relevances, k=5):
    """
    Computes DCG@k for one ranked list.
    """
    relevances = np.asarray(relevances)[:k]
    if len(relevances) == 0:
        return 0.0

    discounts = np.log2(np.arange(2, len(relevances) + 2))
    gains = (2 ** relevances - 1)
    return np.sum(gains / discounts)


def ndcg_at_k_for_group(y_true, y_score, k=5):
    """
    Computes NDCG@k for one search group.
    """
    order = np.argsort(-y_score)
    ranked_relevance = y_true[order]

    ideal_order = np.argsort(-y_true)
    ideal_relevance = y_true[ideal_order]

    dcg = dcg_at_k(ranked_relevance, k=k)
    idcg = dcg_at_k(ideal_relevance, k=k)

    if idcg == 0:
        return 0.0

    return dcg / idcg


def mean_ndcg_at_k(df, y_true_col, y_score_col, group_col="srch_id", k=5):
    """
    Computes mean NDCG@k over all searches.
    """

    scores = []

    for _, group in df.groupby(group_col):
        y_true = group[y_true_col].to_numpy()
        y_score = group[y_score_col].to_numpy()

        scores.append(ndcg_at_k_for_group(y_true, y_score, k=k))

    return np.mean(scores)

Binary Classification model - LGBMClassifier Model

In [21]:
# ---------------------------------------------------
# Binary classification target
# ---------------------------------------------------

y_train_cls = (
    (train_feat["click_bool"] == 1) |
    (train_feat["booking_bool"] == 1)
).astype(int)

y_val_cls = (
    (val_feat["click_bool"] == 1) |
    (val_feat["booking_bool"] == 1)
).astype(int)

# ---------------------------------------------------
# Train classifier
# ---------------------------------------------------
param_grid = {
    "num_leaves": [31, 63],
    "learning_rate": [0.05, 0.03],
    "min_child_samples": [50, 100]
}

keys = list(param_grid.keys())

experiments = [
    dict(zip(keys, values))
    for values in product(*param_grid.values())
]

classifier_results = []

for i, params in enumerate(experiments, start=1):
    print(f"Training classifier {i}/{len(experiments)}")
    print(params)

    classifier = lgb.LGBMClassifier(
        objective="binary",
        device="cpu",

        n_estimators=1000,

        subsample=0.8,
        colsample_bytree=0.8,

        random_state=RANDOM_STATE,
        n_jobs=-1,

        **params
    )

    classifier.fit(
        X_train,
        y_train_cls,
        eval_set=[(X_val, y_val_cls)],
        eval_metric="auc",

        callbacks=[
            lgb.early_stopping(50),
            lgb.log_evaluation(100)
        ]
    )

    # ---------------------------------------------------
    # Predict probabilities
    # ---------------------------------------------------

    preds = classifier.predict_proba(
            X_val,
            num_iteration=classifier.best_iteration_
        )[:, 1]


    # ---------------------------------------------------
    # Evaluate ranking quality using NDCG
    # ---------------------------------------------------

    val_classifier_eval = val_feat[
            ["srch_id", "prop_id", "relevance"]
        ].copy()

    val_classifier_eval["prediction"] = preds

    classifier_ndcg = mean_ndcg_at_k(
        val_classifier_eval,
        y_true_col="relevance",
        y_score_col="prediction",
        group_col="srch_id",
        k=5
    )

    classifier_results.append({
            "experiment": i,

            "num_leaves": params["num_leaves"],
            "learning_rate": params["learning_rate"],
            "min_child_samples": params["min_child_samples"],

            "best_iteration": classifier.best_iteration_,
            "validation_ndcg@5": classifier_ndcg
        })

classifier_results = pd.DataFrame(classifier_results)

classifier_results = classifier_results.sort_values(
        "validation_ndcg@5",
        ascending=False
    )

best_classifier_parameters = {
    "num_leaves": int(classifier_results.iloc[0]["num_leaves"]),
    "learning_rate": float(classifier_results.iloc[0]["learning_rate"]),
    "min_child_samples": int(classifier_results.iloc[0]["min_child_samples"]),
    "n_estimators": int(classifier_results.iloc[0]["best_iteration"])
}

print(best_classifier_parameters)
display(classifier_results)

Training classifier 1/8
{'num_leaves': 31, 'learning_rate': 0.05, 'min_child_samples': 50}
[LightGBM] [Info] Number of positive: 177702, number of negative: 3802337
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.391331 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.044648 -> initscore=-3.063263
[LightGBM] [Info] Start training from score -3.063263
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.749254	valid_0's binary_logloss: 0.16489
Early stopping, best iteration is:
[110]	valid_0's auc: 0.749686	valid_0's binary_logloss: 0.164821
Training classifier 2/8
{'num_leaves': 31, 'learning_rate': 0.05, 'min_child_samples': 100}
[LightGBM] [Info] Number of positive: 177702, number of negative: 3802337
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.387862 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.044648 -> initscore=-3.063263
[LightGBM] [Info] Start training from score -3.063263
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.74925	valid_0's binary_logloss: 0.164914
Early stopping, best iteration is:
[125]	valid_0's auc: 0.750585	valid_0's binary_logloss: 0.164714
Training classifier 3/8
{'num_leaves': 31, 'learning_rate': 0.03, 'min_child_samples': 50}
[LightGBM] [Info] Number of positive: 177702, number of negative: 3802337
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.379568 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.044648 -> initscore=-3.063263
[LightGBM] [Info] Start training from score -3.063263
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.745143	valid_0's binary_logloss: 0.165864
[200]	valid_0's auc: 0.750078	valid_0's binary_logloss: 0.16488
Early stopping, best iteration is:
[190]	valid_0's auc: 0.750317	valid_0's binary_logloss: 0.164775
Training classifier 4/8
{'num_leaves': 31, 'learning_rate': 0.03, 'min_child_samples': 100}
[LightGBM] [Info] Number of positive: 177702, number of negative: 3802337
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.418362 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.044648 -> initscore=-3.063263
[LightGBM] [Info] Start training from score -3.063263
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.745142	valid_0's binary_logloss: 0.165854
[200]	valid_0's auc: 0.750056	valid_0's binary_logloss: 0.164865
Early stopping, best iteration is:
[203]	valid_0's auc: 0.750198	valid_0's binary_logloss: 0.16484
Training classifier 5/8
{'num_leaves': 63, 'learning_rate': 0.05, 'min_child_samples': 50}
[LightGBM] [Info] Number of positive: 177702, number of negative: 3802337
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.408415 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.044648 -> initscore=-3.063263
[LightGBM] [Info] Start training from score -3.063263
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.751281	valid_0's binary_logloss: 0.164713
Early stopping, best iteration is:
[93]	valid_0's auc: 0.751223	valid_0's binary_logloss: 0.164655
Training classifier 6/8
{'num_leaves': 63, 'learning_rate': 0.05, 'min_child_samples': 100}
[LightGBM] [Info] Number of positive: 177702, number of negative: 3802337
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.423403 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.044648 -> initscore=-3.063263
[LightGBM] [Info] Start training from score -3.063263
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.751948	valid_0's binary_logloss: 0.164563
Early stopping, best iteration is:
[94]	valid_0's auc: 0.751919	valid_0's binary_logloss: 0.164538
Training classifier 7/8
{'num_leaves': 63, 'learning_rate': 0.03, 'min_child_samples': 50}
[LightGBM] [Info] Number of positive: 177702, number of negative: 3802337
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.628472 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.044648 -> initscore=-3.063263
[LightGBM] [Info] Start training from score -3.063263
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.748655	valid_0's binary_logloss: 0.16519
Early stopping, best iteration is:
[148]	valid_0's auc: 0.751428	valid_0's binary_logloss: 0.164613
Training classifier 8/8
{'num_leaves': 63, 'learning_rate': 0.03, 'min_child_samples': 100}
[LightGBM] [Info] Number of positive: 177702, number of negative: 3802337
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.395577 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.044648 -> initscore=-3.063263
[LightGBM] [Info] Start training from score -3.063263
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.748602	valid_0's binary_logloss: 0.16519
[200]	valid_0's auc: 0.750564	valid_0's binary_logloss: 0.165195
Early stopping, best iteration is:
[166]	valid_0's auc: 0.751562	valid_0's binary_logloss: 0.164637
{'num_leaves': 63, 'learning_rate': 0.03, 'min_child_samples': 100, 'n_estimators': 166}

,experiment,num_leaves,learning_rate,min_child_samples,best_iteration,validation_ndcg@5
7,8,63,0.03,100,166,0.373555
6,7,63,0.03,50,148,0.372937
4,5,63,0.05,50,93,0.372492
5,6,63,0.05,100,94,0.371863
1,2,31,0.05,100,125,0.371832
3,4,31,0.03,100,203,0.371473
2,3,31,0.03,50,190,0.370823
0,1,31,0.05,50,110,0.370019

LGBMRanker Model

In [54]:
# # ---------------------------------------------------
# # Hyperparameter grid
# # ---------------------------------------------------

# # param_grid = {
# #     "num_leaves": [31, 63, 127],
# #     "learning_rate": [0.05, 0.01, 0.1],
# #     "min_child_samples": [50, 100, 200]
# # }
# # -> num_leaves = 127, lr = 0.01, min_child_samples = 200 -> 0.382248


# # param_grid = {
# #     "num_leaves": [95, 127, 191, 255],
# #     "learning_rate": [0.005, 0.01, 0.02, 0.03],
# #     "min_child_samples": [150, 200, 300, 500]
# # }
# # -> num_leaves = 255, lr = 0.02, min_child_samples = 500 submitted -> 0.385801

# # param_grid = {
# #     "num_leaves": [255, 319],
# #     "learning_rate": [0.02, 0.025],
# #     "min_child_samples": [500, 700]
# # }
# # -> num_leaves = 255, lr = 0.02, min_child_samples = 500 -> 0.385801


# # param_grid = {
# #     "num_leaves": [191, 255, 319, 383],
# #     "learning_rate": [0.015, 0.02, 0.025, 0.03],
# #     "min_child_samples": [300, 500, 700, 900]
# # }
# # -> num_leaves = 383, lr = 0.02, min_child_samples = 900 -> 0.386670


# # Create all parameter combinations
# keys = list(param_grid.keys())

# experiments = [
#     dict(zip(keys, values))
#     for values in product(*param_grid.values())
# ]

# print("Total experiments:", len(experiments))

# # ---------------------------------------------------
# # Run experiments
# # ---------------------------------------------------

# tuning_results = []

# for i, params in enumerate(experiments, start=1):

#     print("=" * 60)
#     print(f"Experiment {i}/{len(experiments)}")
#     print(params)

#     ranker = lgb.LGBMRanker(
#         objective="lambdarank",
#         metric="ndcg",
#         ndcg_eval_at=[5],
#         boosting_type="gbdt",
#         device="cpu",
#         n_estimators=1000,

#         subsample=0.8,
#         colsample_bytree=0.8,

#         random_state=RANDOM_STATE,
#         n_jobs=-1,

#         **params
#     )

#     ranker.fit(
#         X_train,
#         y_train,
#         group=group_train,

#         eval_set=[(X_val, y_val)],
#         eval_group=[group_val],
#         eval_at=[5],

#         callbacks=[
#             lgb.early_stopping(stopping_rounds=50),
#             lgb.log_evaluation(period=100)
#         ]
#     )

#     # -------------------------
#     # Predict validation scores
#     # -------------------------

#     preds = ranker.predict(
#         X_val,
#         num_iteration=ranker.best_iteration_
#     )

#     # -------------------------
#     # Compute validation NDCG@5
#     # -------------------------

#     tmp = val_feat[["srch_id", "prop_id", "relevance"]].copy()

#     tmp["prediction"] = preds

#     score = mean_ndcg_at_k(
#         tmp,
#         y_true_col="relevance",
#         y_score_col="prediction",
#         group_col="srch_id",
#         k=5
#     )

#     # -------------------------
#     # Save results
#     # -------------------------

#     tuning_results.append({
#         "experiment": i,

#         "num_leaves": params["num_leaves"],
#         "learning_rate": params["learning_rate"],
#         "min_child_samples": params["min_child_samples"],

#         "best_iteration": ranker.best_iteration_,
#         "validation_ndcg@5": score
#     })

# # ---------------------------------------------------
# # Final results table
# # ---------------------------------------------------

# tuning_results = pd.DataFrame(tuning_results)

# tuning_results = tuning_results.sort_values(
#     "validation_ndcg@5",
#     ascending=False
# )

# best_parameters = {
#     "num_leaves": int(tuning_results.iloc[0]["num_leaves"]),
#     "learning_rate": float(tuning_results.iloc[0]["learning_rate"]),
#     "min_child_samples": int(tuning_results.iloc[0]["min_child_samples"]),
#     "n_estimators": int(tuning_results.iloc[0]["best_iteration"])
# }

# display(tuning_results)

# ---------------------------------------------------
# Regularization tuning around the best model so far
# ---------------------------------------------------

# Best core parameters found in the previous grid search:
# num_leaves = 383, learning_rate = 0.02, min_child_samples = 900
# validation NDCG@5 = 0.386670

# ---------------------------------------------------
# Cell A: Regularization and sampling tuning
# ---------------------------------------------------
# We already found a strong core LightGBM Ranker setting:
# num_leaves = 383
# learning_rate = 0.02
# min_child_samples = 900
# validation NDCG@5 = 0.386670
#
# Now we keep these core parameters fixed and tune:
# - reg_lambda: L2 regularization
# - reg_alpha: L1 regularization
# - subsample: row sampling per tree
# - colsample_bytree: feature sampling per tree

from itertools import product
import pandas as pd
import lightgbm as lgb

# Best core parameters from previous grid search
base_params = {
    "num_leaves": 383,
    "learning_rate": 0.02,
    "min_child_samples": 900
}

# 4 x 2 x 2 x 2 = 32 experiments
param_grid = {
    "reg_lambda": [0.0, 1.0, 5.0, 10.0],
    "reg_alpha": [0.0, 0.1],
    "subsample": [0.8, 0.9],
    "colsample_bytree": [0.8, 0.9]
}

# Create all parameter combinations
keys = list(param_grid.keys())

experiments = [
    dict(zip(keys, values))
    for values in product(*param_grid.values())
]

print("Total experiments:", len(experiments))

# ---------------------------------------------------
# Run experiments
# ---------------------------------------------------

tuning_results = []

for i, params in enumerate(experiments, start=1):

    # Combine fixed best parameters with the current regularization/sampling parameters
    all_params = {**base_params, **params}

    print("=" * 60)
    print(f"Experiment {i}/{len(experiments)}")
    print(all_params)

    ranker = lgb.LGBMRanker(
        objective="lambdarank",
        metric="ndcg",
        ndcg_eval_at=[5],
        boosting_type="gbdt",
        device="cpu",

        # 1000 is enough here because the previous best stopped at 202 trees
        n_estimators=1000,

        random_state=RANDOM_STATE,
        n_jobs=-1,

        **all_params
    )

    ranker.fit(
        X_train,
        y_train,
        group=group_train,

        eval_set=[(X_val, y_val)],
        eval_group=[group_val],
        eval_at=[5],

        callbacks=[
            lgb.early_stopping(stopping_rounds=50),
            lgb.log_evaluation(period=100)
        ]
    )

    # ---------------------------------------------------
    # Predict validation scores
    # ---------------------------------------------------

    preds = ranker.predict(
        X_val,
        num_iteration=ranker.best_iteration_
    )

    # ---------------------------------------------------
    # Compute validation NDCG@5
    # ---------------------------------------------------

    tmp = val_feat[["srch_id", "prop_id", "relevance"]].copy()
    tmp["prediction"] = preds

    score = mean_ndcg_at_k(
        tmp,
        y_true_col="relevance",
        y_score_col="prediction",
        group_col="srch_id",
        k=5
    )

    # ---------------------------------------------------
    # Save experiment results
    # ---------------------------------------------------

    tuning_results.append({
        "experiment": i,

        "num_leaves": all_params["num_leaves"],
        "learning_rate": all_params["learning_rate"],
        "min_child_samples": all_params["min_child_samples"],

        "reg_lambda": all_params["reg_lambda"],
        "reg_alpha": all_params["reg_alpha"],
        "subsample": all_params["subsample"],
        "colsample_bytree": all_params["colsample_bytree"],

        "best_iteration": ranker.best_iteration_,
        "validation_ndcg@5": score
    })

# ---------------------------------------------------
# Final results table
# ---------------------------------------------------

tuning_results = pd.DataFrame(tuning_results)

tuning_results = tuning_results.sort_values(
    "validation_ndcg@5",
    ascending=False
).reset_index(drop=True)

best_row = tuning_results.iloc[0]

best_parameters = {
    "num_leaves": int(best_row["num_leaves"]),
    "learning_rate": float(best_row["learning_rate"]),
    "min_child_samples": int(best_row["min_child_samples"]),

    "reg_lambda": float(best_row["reg_lambda"]),
    "reg_alpha": float(best_row["reg_alpha"]),
    "subsample": float(best_row["subsample"]),
    "colsample_bytree": float(best_row["colsample_bytree"]),

    "n_estimators": int(best_row["best_iteration"])
}

print("Best parameters:")
print(best_parameters)

print("\nBest validation NDCG@5:")
print(best_row["validation_ndcg@5"])

display(tuning_results)

Total experiments: 32
============================================================
Experiment 1/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 0.0, 'reg_alpha': 0.0, 'subsample': 0.8, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.519241 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.38379
[200]	valid_0's ndcg@5: 0.386424
Early stopping, best iteration is:
[202]	valid_0's ndcg@5: 0.38667

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 2/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 0.0, 'reg_alpha': 0.0, 'subsample': 0.8, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.530863 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.381392
[200]	valid_0's ndcg@5: 0.385582
Early stopping, best iteration is:
[247]	valid_0's ndcg@5: 0.386269

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 3/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 0.0, 'reg_alpha': 0.0, 'subsample': 0.9, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.444922 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.38379
[200]	valid_0's ndcg@5: 0.386424
Early stopping, best iteration is:
[202]	valid_0's ndcg@5: 0.38667

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 4/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 0.0, 'reg_alpha': 0.0, 'subsample': 0.9, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.482024 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.381392
[200]	valid_0's ndcg@5: 0.385582
Early stopping, best iteration is:
[247]	valid_0's ndcg@5: 0.386269

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 5/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 0.0, 'reg_alpha': 0.1, 'subsample': 0.8, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.488938 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.380464
[200]	valid_0's ndcg@5: 0.381475
Early stopping, best iteration is:
[160]	valid_0's ndcg@5: 0.382452

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 6/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 0.0, 'reg_alpha': 0.1, 'subsample': 0.8, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.529162 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.380404
[200]	valid_0's ndcg@5: 0.380874
Early stopping, best iteration is:
[246]	valid_0's ndcg@5: 0.381519

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 7/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 0.0, 'reg_alpha': 0.1, 'subsample': 0.9, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.504104 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.380464
[200]	valid_0's ndcg@5: 0.381475
Early stopping, best iteration is:
[160]	valid_0's ndcg@5: 0.382452

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 8/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 0.0, 'reg_alpha': 0.1, 'subsample': 0.9, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.511574 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.380404
[200]	valid_0's ndcg@5: 0.380874
Early stopping, best iteration is:
[246]	valid_0's ndcg@5: 0.381519

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 9/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 1.0, 'reg_alpha': 0.0, 'subsample': 0.8, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.510742 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.383022
[200]	valid_0's ndcg@5: 0.385376
Early stopping, best iteration is:
[243]	valid_0's ndcg@5: 0.386425

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 10/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 1.0, 'reg_alpha': 0.0, 'subsample': 0.8, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.547483 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.382749
[200]	valid_0's ndcg@5: 0.384498
Early stopping, best iteration is:
[237]	valid_0's ndcg@5: 0.38574

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 11/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 1.0, 'reg_alpha': 0.0, 'subsample': 0.9, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.469160 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.383022
[200]	valid_0's ndcg@5: 0.385376
Early stopping, best iteration is:
[243]	valid_0's ndcg@5: 0.386425

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 12/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 1.0, 'reg_alpha': 0.0, 'subsample': 0.9, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.432773 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.382749
[200]	valid_0's ndcg@5: 0.384498
Early stopping, best iteration is:
[237]	valid_0's ndcg@5: 0.38574

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 13/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 1.0, 'reg_alpha': 0.1, 'subsample': 0.8, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.548210 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.380136
[200]	valid_0's ndcg@5: 0.381526
Early stopping, best iteration is:
[191]	valid_0's ndcg@5: 0.381862

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 14/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 1.0, 'reg_alpha': 0.1, 'subsample': 0.8, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.457672 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.381373
[200]	valid_0's ndcg@5: 0.381982
Early stopping, best iteration is:
[245]	valid_0's ndcg@5: 0.382788

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 15/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 1.0, 'reg_alpha': 0.1, 'subsample': 0.9, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.470880 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.380136
[200]	valid_0's ndcg@5: 0.381526
Early stopping, best iteration is:
[191]	valid_0's ndcg@5: 0.381862

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 16/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 1.0, 'reg_alpha': 0.1, 'subsample': 0.9, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.655573 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.381373
[200]	valid_0's ndcg@5: 0.381982
Early stopping, best iteration is:
[245]	valid_0's ndcg@5: 0.382788

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 17/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 5.0, 'reg_alpha': 0.0, 'subsample': 0.8, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.489364 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.384135
[200]	valid_0's ndcg@5: 0.386427
Early stopping, best iteration is:
[239]	valid_0's ndcg@5: 0.387124

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 18/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 5.0, 'reg_alpha': 0.0, 'subsample': 0.8, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.477610 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.382446
[200]	valid_0's ndcg@5: 0.38542
Early stopping, best iteration is:
[237]	valid_0's ndcg@5: 0.385836

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 19/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 5.0, 'reg_alpha': 0.0, 'subsample': 0.9, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.481025 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.384135
[200]	valid_0's ndcg@5: 0.386427
Early stopping, best iteration is:
[239]	valid_0's ndcg@5: 0.387124

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 20/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 5.0, 'reg_alpha': 0.0, 'subsample': 0.9, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.524636 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.382446
[200]	valid_0's ndcg@5: 0.38542
Early stopping, best iteration is:
[237]	valid_0's ndcg@5: 0.385836

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 21/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 5.0, 'reg_alpha': 0.1, 'subsample': 0.8, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.482610 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.381243
[200]	valid_0's ndcg@5: 0.381579
Early stopping, best iteration is:
[159]	valid_0's ndcg@5: 0.382064

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 22/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 5.0, 'reg_alpha': 0.1, 'subsample': 0.8, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.504201 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.380273
[200]	valid_0's ndcg@5: 0.381191
Early stopping, best iteration is:
[153]	valid_0's ndcg@5: 0.38191

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 23/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 5.0, 'reg_alpha': 0.1, 'subsample': 0.9, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.498124 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.381243
[200]	valid_0's ndcg@5: 0.381579
Early stopping, best iteration is:
[159]	valid_0's ndcg@5: 0.382064

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 24/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 5.0, 'reg_alpha': 0.1, 'subsample': 0.9, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.520535 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.380273
[200]	valid_0's ndcg@5: 0.381191
Early stopping, best iteration is:
[153]	valid_0's ndcg@5: 0.38191

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 25/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 10.0, 'reg_alpha': 0.0, 'subsample': 0.8, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.607661 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.383334
[200]	valid_0's ndcg@5: 0.385888
[300]	valid_0's ndcg@5: 0.386706
Early stopping, best iteration is:
[286]	valid_0's ndcg@5: 0.387156

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 26/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 10.0, 'reg_alpha': 0.0, 'subsample': 0.8, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.516445 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.382157
[200]	valid_0's ndcg@5: 0.384984
Early stopping, best iteration is:
[244]	valid_0's ndcg@5: 0.386328

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 27/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 10.0, 'reg_alpha': 0.0, 'subsample': 0.9, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.485599 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.383334
[200]	valid_0's ndcg@5: 0.385888
[300]	valid_0's ndcg@5: 0.386706
Early stopping, best iteration is:
[286]	valid_0's ndcg@5: 0.387156

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 28/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 10.0, 'reg_alpha': 0.0, 'subsample': 0.9, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.466074 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.382157
[200]	valid_0's ndcg@5: 0.384984
Early stopping, best iteration is:
[244]	valid_0's ndcg@5: 0.386328

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 29/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 10.0, 'reg_alpha': 0.1, 'subsample': 0.8, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.462835 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.380749
[200]	valid_0's ndcg@5: 0.381877
Early stopping, best iteration is:
[155]	valid_0's ndcg@5: 0.382397

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 30/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 10.0, 'reg_alpha': 0.1, 'subsample': 0.8, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.496795 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.381005
[200]	valid_0's ndcg@5: 0.38069
Early stopping, best iteration is:
[153]	valid_0's ndcg@5: 0.382003

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 31/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 10.0, 'reg_alpha': 0.1, 'subsample': 0.9, 'colsample_bytree': 0.8}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.477632 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.380749
[200]	valid_0's ndcg@5: 0.381877
Early stopping, best iteration is:
[155]	valid_0's ndcg@5: 0.382397

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

============================================================
Experiment 32/32
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 10.0, 'reg_alpha': 0.1, 'subsample': 0.9, 'colsample_bytree': 0.9}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.486836 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16588
[LightGBM] [Info] Number of data points in the train set: 3980039, number of used features: 168
Training until validation scores don't improve for 50 rounds
[100]	valid_0's ndcg@5: 0.381005
[200]	valid_0's ndcg@5: 0.38069
Early stopping, best iteration is:
[153]	valid_0's ndcg@5: 0.382003

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

Best parameters:
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 10.0, 'reg_alpha': 0.0, 'subsample': 0.9, 'colsample_bytree': 0.8, 'n_estimators': 286}

Best validation NDCG@5:
0.3871559317282132

,experiment,num_leaves,learning_rate,min_child_samples,reg_lambda,reg_alpha,subsample,colsample_bytree,best_iteration,validation_ndcg@5
0,27,383,0.02,900,10.0,0.0,0.9,0.8,286,0.387156
1,25,383,0.02,900,10.0,0.0,0.8,0.8,286,0.387156
2,17,383,0.02,900,5.0,0.0,0.8,0.8,239,0.387124
3,19,383,0.02,900,5.0,0.0,0.9,0.8,239,0.387124
4,1,383,0.02,900,0.0,0.0,0.8,0.8,202,0.386670
5,3,383,0.02,900,0.0,0.0,0.9,0.8,202,0.386670
6,9,383,0.02,900,1.0,0.0,0.8,0.8,243,0.386425
7,11,383,0.02,900,1.0,0.0,0.9,0.8,243,0.386425
8,28,383,0.02,900,10.0,0.0,0.9,0.9,244,0.386328
9,26,383,0.02,900,10.0,0.0,0.8,0.9,244,0.386328
10,4,383,0.02,900,0.0,0.0,0.9,0.9,247,0.386269
11,2,383,0.02,900,0.0,0.0,0.8,0.9,247,0.386269
12,20,383,0.02,900,5.0,0.0,0.9,0.9,237,0.385836
13,18,383,0.02,900,5.0,0.0,0.8,0.9,237,0.385836
14,10,383,0.02,900,1.0,0.0,0.8,0.9,237,0.385740
15,12,383,0.02,900,1.0,0.0,0.9,0.9,237,0.385740
16,16,383,0.02,900,1.0,0.1,0.9,0.9,245,0.382788
17,14,383,0.02,900,1.0,0.1,0.8,0.9,245,0.382788
18,7,383,0.02,900,0.0,0.1,0.9,0.8,160,0.382452
19,5,383,0.02,900,0.0,0.1,0.8,0.8,160,0.382452
20,29,383,0.02,900,10.0,0.1,0.8,0.8,155,0.382397
21,31,383,0.02,900,10.0,0.1,0.9,0.8,155,0.382397
22,21,383,0.02,900,5.0,0.1,0.8,0.8,159,0.382064
23,23,383,0.02,900,5.0,0.1,0.9,0.8,159,0.382064
24,30,383,0.02,900,10.0,0.1,0.8,0.9,153,0.382003
25,32,383,0.02,900,10.0,0.1,0.9,0.9,153,0.382003
26,24,383,0.02,900,5.0,0.1,0.9,0.9,153,0.381910
27,22,383,0.02,900,5.0,0.1,0.8,0.9,153,0.381910
28,15,383,0.02,900,1.0,0.1,0.9,0.8,191,0.381862
29,13,383,0.02,900,1.0,0.1,0.8,0.8,191,0.381862
30,8,383,0.02,900,0.0,0.1,0.9,0.9,246,0.381519
31,6,383,0.02,900,0.0,0.1,0.8,0.9,246,0.381519

In [55]:
# # Rebuild feature list from full training data.
# final_feature_cols = [
#     col for col in full_train_feat.columns
#     if col not in NON_FEATURE_COLS
#     and pd.api.types.is_numeric_dtype(full_train_feat[col])
# ]

# # Ensure test has all final feature columns.
# missing_in_test = [col for col in final_feature_cols if col not in test_feat.columns]
# print("Missing features in test:", missing_in_test)

# # Sort by srch_id to ensure correct grouping for LightGBM ranker.
# full_train_feat = full_train_feat.sort_values("srch_id").reset_index(drop=True)
# test_feat = test_feat.sort_values("srch_id").reset_index(drop=True)

# X_full = full_train_feat[final_feature_cols]
# y_full = full_train_feat["relevance"].astype(int)
# group_full = full_train_feat.groupby("srch_id").size().to_numpy()

# X_test = test_feat[final_feature_cols]

# print("X_full:", X_full.shape)
# print("X_test:", X_test.shape)
# print("Number of final features:", len(final_feature_cols))

# ---------------------------------------------------
# Prepare full training and test matrices for final model
# ---------------------------------------------------
# This cell prepares the full training set and test set using the same feature columns.
# It does not train the model yet.

# Columns that should not be used as model input.
# srch_id and prop_id are identifiers.
# date_time is not used directly because we already extracted date/time features.
# click_bool, booking_bool, gross_bookings_usd, position, and relevance are target-related or unavailable in test.
NON_FEATURE_COLS = [
    "srch_id",
    "prop_id",
    "date_time",
    "click_bool",
    "booking_bool",
    "gross_bookings_usd",
    "position",
    "relevance"
]

# Rebuild feature list from full training data.
# Only numeric columns are used by the final LightGBM Ranker.
final_feature_cols = [
    col for col in full_train_feat.columns
    if col not in NON_FEATURE_COLS
    and pd.api.types.is_numeric_dtype(full_train_feat[col])
]

# Ensure test has all final feature columns.
missing_in_test = [col for col in final_feature_cols if col not in test_feat.columns]
print("Missing features in test:", missing_in_test)

if len(missing_in_test) > 0:
    raise ValueError("Some final training features are missing in the test set.")

# Sort by srch_id to ensure correct grouping for LightGBM ranker.
# LightGBM needs group sizes to match the row order.
full_train_feat = full_train_feat.sort_values("srch_id").reset_index(drop=True)
test_feat = test_feat.sort_values("srch_id").reset_index(drop=True)

# Create final training matrix, target, group sizes, and test matrix.
X_full = full_train_feat[final_feature_cols]
y_full = full_train_feat["relevance"].astype(int)
group_full = full_train_feat.groupby("srch_id").size().to_numpy()

X_test = test_feat[final_feature_cols]

print("X_full:", X_full.shape)
print("X_test:", X_test.shape)
print("Number of final features:", len(final_feature_cols))

Missing features in test: []
X_full: (4958347, 169)
X_test: (4959183, 169)
Number of final features: 169

In [56]:
# # Use the best iteration from validation if available.
# # If early stopping stopped at e.g. 350 trees, train final model with that many trees.
# best_cls_n_estimators = ranker.best_iteration_

# final_classifier = lgb.LGBMClassifier(
#     objective="binary",

#     n_estimators=best_cls_n_estimators,
#     num_leaves=best_classifier_parameters["num_leaves"],
#     learning_rate=best_classifier_parameters["learning_rate"],
#     min_child_samples=best_classifier_parameters["min_child_samples"],

#     subsample=0.8,
#     colsample_bytree=0.8,

#     random_state=RANDOM_STATE,
#     n_jobs=-1
# )

In [57]:
# # Use the best iteration from validation if available.
# # If early stopping stopped at e.g. 350 trees, train final model with that many trees.
# # best_n_estimators = ranker.best_iteration_
# best_n_estimators = best_parameters["n_estimators"] #------------------------------------------------------------------!!!!!!!!!!

# print("Training final model with n_estimators =", best_n_estimators)

# final_ranker = lgb.LGBMRanker(
#     objective="lambdarank",
#     metric="ndcg",
#     ndcg_eval_at=[5],
#     boosting_type="gbdt",

#     n_estimators=best_n_estimators,
#     learning_rate=best_parameters["learning_rate"],
#     num_leaves=best_parameters["num_leaves"],
#     max_depth=-1,
#     min_child_samples=best_parameters["min_child_samples"],
#     subsample=0.8,
#     colsample_bytree=0.8,
#     random_state=RANDOM_STATE,
#     n_jobs=-1
# )

# final_ranker.fit(
#     X_full,
#     y_full,
#     group=group_full
# )

# ---------------------------------------------------
# Train final LightGBM Ranker on the full training set
# ---------------------------------------------------
# This uses the best parameters found during validation tuning.
# The final model is trained on the full training data.

best_n_estimators = best_parameters["n_estimators"]

print("Training final model with parameters:")
print(best_parameters)

final_ranker = lgb.LGBMRanker(
    objective="lambdarank",
    metric="ndcg",
    ndcg_eval_at=[5],
    boosting_type="gbdt",

    n_estimators=best_n_estimators,
    learning_rate=best_parameters["learning_rate"],
    num_leaves=best_parameters["num_leaves"],
    max_depth=-1,
    min_child_samples=best_parameters["min_child_samples"],

    reg_lambda=best_parameters["reg_lambda"],
    reg_alpha=best_parameters["reg_alpha"],
    subsample=best_parameters["subsample"],
    colsample_bytree=best_parameters["colsample_bytree"],

    random_state=RANDOM_STATE,
    n_jobs=-1
)

final_ranker.fit(
    X_full,
    y_full,
    group=group_full
)

print("Final ranker trained.")

Training final model with parameters:
{'num_leaves': 383, 'learning_rate': 0.02, 'min_child_samples': 900, 'reg_lambda': 10.0, 'reg_alpha': 0.0, 'subsample': 0.9, 'colsample_bytree': 0.8, 'n_estimators': 286}

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.574145 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 16596
[LightGBM] [Info] Number of data points in the train set: 4958347, number of used features: 167
Final ranker trained.

In [58]:
# Check which datetime columns are still in test_feat
test_feat.select_dtypes(include=["datetime64", "datetime64[ns]"]).columns

Index(['date_time'], dtype='str')

In [59]:
# test_scores = final_ranker.predict(test_feat)

feature_cols = final_ranker.feature_name_

test_scores = final_ranker.predict(test_feat[feature_cols])

submission = test_feat[["srch_id", "prop_id"]].copy()
submission["score"] = test_scores

submission = submission.sort_values(
    ["srch_id", "score"],
    ascending=[True, False]
)

# submission = submission[["srch_id", "prop_id"]]
# submission.to_csv("submission.csv", index=False)

# submission = test_feat[["srch_id", "prop_id"]].copy()
# submission["score"] = test_scores

# # Sort hotels within each search by predicted score descending.
# submission = submission.sort_values(
#     ["srch_id", "score"],
#     ascending=[True, False]
# )

# # Required Kaggle format:
# # SearchId,PropertyId
# submission = submission.rename(columns={
#     "srch_id": "SearchId",
#     "prop_id": "PropertyId"
# })

submission = submission[["srch_id", "prop_id"]]

display(submission.head(30))

submission_path = "submission_lgbm_ranker.csv"
submission.to_csv(submission_path, index=False)

print("Saved submission to:", submission_path)
print("Submission shape:", submission.shape)

/opt/anaconda3/envs/dmt-a2/lib/python3.11/site-packages/lightgbm/sklearn.py:861: UserWarning: Found 'ndcg_eval_at' in params. Will use it instead of 'eval_at' argument
  _log_warning(f"Found '{alias}' in params. Will use it instead of 'eval_at' argument")

    srch_id  prop_id
6         1    99484
16        1    54937
27        1    28181
26        1    61934
20        1    24194
21        1    34263
23        1    50162
7         1    95031
2         1    90385
22        1     5543
0         1     3180
11        1    74045
15        1    63894
9         1    82231
10        1    78599
17        1    72090
5         1   128085
12        1   123675
19        1    22393
18        1    14142
8         1    94729
28        1    37567
13        1    73666
1         1   139162
14        1    89466
24        1    56050
25        1    61632
4         1   128871
3         1   134992
36        3   131940

Saved submission to: submission_lgbm_ranker.csv
Submission shape: (4959183, 2)

In [60]:
final_feature_importance = pd.DataFrame({
    # "feature": final_feature_cols,
    "feature": final_ranker.feature_name_,
    "importance": final_ranker.feature_importances_
}).sort_values("importance", ascending=False)

display(final_feature_importance.head(50))

final_feature_importance.to_csv("feature_importance_lgbm_ranker.csv", index=False)
print("Saved feature importance to feature_importance_lgbm_ranker.csv")

                             feature  importance
10         prop_log_historical_price        3661
154             prop_id_median_price        3306
160     prop_id_mean_location_score2        3132
156           prop_id_mean_log_price        3110
11                         price_usd        2949
152                    prop_id_count        2878
147  location2_diff_from_search_mean        2733
129         price_pct_rank_in_search        2670
153               prop_id_mean_price        2561
137          star_pct_rank_in_search        2530
134       star_diff_from_search_mean        2521
146  location1_diff_from_search_mean        2511
155                prop_id_std_price        2478
8               prop_location_score1        2447
140     review_diff_from_search_mean        2443
9               prop_location_score2        2321
143        review_pct_rank_in_search        2229
151       promotion_above_search_avg        2162
161      prop_id_mean_promotion_flag        2110
127     price_ratio_to_search_median        2015
168                  prop_dest_count        1929
144            search_location1_mean        1920
125       price_diff_from_search_min        1861
128             price_rank_in_search        1790
149     location2_pct_rank_in_search        1752
162                    dest_id_count        1745
145            search_location2_mean        1701
22                       random_bool        1685
132                 search_star_mean        1628
126       price_ratio_to_search_mean        1619
164             dest_id_median_price        1582
163               dest_id_mean_price        1573
123      price_diff_from_search_mean        1561
124    price_diff_from_search_median        1455
166        dest_id_mean_review_score        1448
15               srch_booking_window        1447
136              star_rank_in_search        1422
165          dest_id_mean_starrating        1348
167     dest_id_mean_location_score2        1221
131  log_price_diff_from_search_mean        1218
138               search_review_mean        1205
142            review_rank_in_search        1196
122                 search_price_max        1191
21         orig_destination_distance        1132
13               srch_destination_id         889
4                    prop_country_id         846
148         location2_rank_in_search         825
150            search_promotion_rate         806
121                 search_price_min         803
3               visitor_hist_adr_usd         756

Saved feature importance to feature_importance_lgbm_ranker.csv